plugins {
	id 'org.springframework.boot' version '3.5.9'
}

group = 'com.dewple'
version = '0.0.1-SNAPSHOT'
description = 'App Worker Service'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	// Domain Modules
	implementation project(":modules:common")
	implementation project(":modules:user")
	implementation project(":modules:club")
	implementation project(":modules:activity")
	implementation project(":modules:organization")
	implementation project(":modules:recruitment")

	// Web
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	// Security
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// WebSocket
	implementation 'org.springframework.boot:spring-boot-starter-websocket'

	// SQS Listener
	implementation "io.awspring.cloud:spring-cloud-aws-starter-sqs"

	// SES
	implementation "io.awspring.cloud:spring-cloud-aws-starter-ses"

	// WebClient
	implementation "org.springframework.boot:spring-boot-starter-webflux"

	// DB
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'org.postgresql:postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
