plugins {
	id 'org.springframework.boot' version '3.5.9'
}

group = 'com.dewple'
version = '0.0.1-SNAPSHOT'
description = 'App API Auth Service'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	// Domain Modules
	implementation project(":modules:common")
	implementation project(":modules:user")
	implementation project(":modules:club")
	implementation project(":modules:activity")
	implementation project(":modules:organization")
	implementation project(":modules:recruitment")

	// Web/API
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Security
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// DB
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'
	runtimeOnly 'org.postgresql:postgresql'

	// AWS
	implementation "io.awspring.cloud:spring-cloud-aws-starter-sqs"
	implementation "io.awspring.cloud:spring-cloud-aws-starter-s3"

	// Swagger
	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.15"

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
