spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      "local": "localPort, localRDB, localJPA, localAws, localSecret, localSMS, localSES"
      "dev": "devPort, devRDB, devJPA, devAws, devSecret, devSMS, devSES"
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
