-- V8: 동아리 삭제 투표/유예 기능

ALTER TABLE club ADD COLUMN IF NOT EXISTS deletion_status VARCHAR(20) NOT NULL DEFAULT 'NONE';
ALTER TABLE club ADD COLUMN IF NOT EXISTS deletion_requested_at TIMESTAMPTZ;
ALTER TABLE club ADD COLUMN IF NOT EXISTS deletion_approved_at TIMESTAMPTZ;
ALTER TABLE club ADD COLUMN IF NOT EXISTS scheduled_delete_at TIMESTAMPTZ;
ALTER TABLE club ADD COLUMN IF NOT EXISTS is_sanction_deletion BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS club_deletion_vote (
    id BIGSERIAL PRIMARY KEY,
    club_id BIGINT NOT NULL REFERENCES club(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    is_approved BOOLEAN,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
