name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set application-dev.yaml for app-api-auth
        env:
          APPLICATION_DEV_YML: ${{ secrets.APPLICATION_DEV_API_YML }}
        run: echo "$APPLICATION_DEV_YML" > apps/app-api-auth/src/main/resources/application-dev.yaml

      - name: Set application-dev.yaml for app-worker
        env:
          APPLICATION_WORKER_YML: ${{ secrets.APPLICATION_DEV_WORKER_YML }}
        run: echo "$APPLICATION_WORKER_YML" > apps/app-worker/src/main/resources/application-dev.yaml

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: dev
        run: ./gradlew test
